### ISSUE TITLE
Implement Timetabling for Meet Command

### ISSUE THREAD

**Issue by mynameizzhafeez** [AY2223S2-CS2103T-W14-2/tp#141]
## Russell's TODO
- [x] Scheduler's Logic
- [x] New Timetable, Module, Lesson classes
- [x] Integrate with Meet Command

## Kenny's TODO
- [x] Parse Module Information
- [x] Modify TagCommand and UnTag Command to attach the Class Slots (LEC3, T12) to each person.
- [x] Map each class slot to a particular venue/location.
> Modify meet command such that each location suggestion comes equipped with a few suggested timings (now, meet command suggests 10 locations (AMK Hub, NEX,…). What is required is (AMK Hub @ Monday 9am, NEX @ Thursday 6pm,…)

## After the above are done, Integrator's TODO
- [x] Integrate functionality of Meet with Tag and Untag Command
- [x] Set meeting spot and time on UI.

**Comment by russelltankaimin** [comment]
Completed
