### ISSUE TITLE
[Untag Command] Untag user modules also removes tag from every contact who also has that module.

### ISSUE THREAD

**Issue by russelltankaimin** [AY2223S2-CS2103T-W14-2/tp#252]
## Reproduce
Untag module XXXX from user
Go to a contact you know has XXXX or simply `find XXXX`

## Expected
List of people with `XXXX` still tagged to them.

## Actual
Empty list

**Comment by mynameizzhafeez** [comment]
It doesn't. The reason why the module does not show up on the person list is because it is no longer a common module.
