### ISSUE TITLE
[PE-D][Tester C] Profile panel overspills when there are too many modules/groups

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W14-2/tp#287]
Suggestion: could make it so that the user can scroll if there are too many things to display in the profile panel

![Screenshot 2023-03-31 at 2.40.08 PM.png](https://raw.githubusercontent.com/cyiting/ped/main/files/83bed8cc-85d9-49fb-baf6-7e3461bf3daf.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: cyiting/ped#6

**Comment by russelltankaimin** [comment]
not in scope.
