### ISSUE TITLE
[PE-D][Tester B] Unable to View Timings for Modules 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W14-2/tp#293]
The buttons for modules enlarge when hovered over which implies they are clickable but no information appears when they are clicked. Also, when modules are added the timings (for said modules) are also added but after they are added you can't access the timings anymore to refer back. 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: cmang12/ped#7

**Comment by russelltankaimin** [comment]
not in scope!!!
