### ISSUE TITLE
[PE-D][Tester C] Able to untag non-existent tags

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W14-2/tp#318]
To reproduce error: view any contact and untag any tag that does not exist such as "g/ASDFGGK"

Command is accepted and command result box displays "Group(s) untagged to Person!"

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: cyiting/ped#13

**Comment by russelltankaimin** [comment]
## TODO + extension to tag.
Tag should check if the tag exists already.
Throw exception when tag exists but getting tagged again (Tag already exists)
Exception message should show what tag is present + disallow execution (even if its multiple tagging at once)

Similarly for untag
Untag should check if tag is actually there, else throw exception : E.g Tag not actually there

Ensure duplicate tags in command will throw exception.

**Command result box should be more explicit in what is being tagged**
