### ISSUE TITLE
[PE-D][Tester C] add command suddenly stopped working

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W14-2/tp#319]
I'm not sure how I got it to be like that but I was testing the commands and suddenly the add command stopped working. As shown in the video, I tried all the other commands and they seem to work fine, I could also do "add n/Ritchie Thompson" and it would throw me the correct error, i.e. "This person already exists in the address book" but anytime I tried to add someone new the command isn't accepted and no error message is thrown either.

<i><video controls><source src="https://raw.githubusercontent.com/cyiting/ped/main/files/8cde3528-14cd-426e-8b49-b2d1b744953e.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/cyiting/ped/main/files/8cde3528-14cd-426e-8b49-b2d1b744953e.mp4</i>

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: cyiting/ped#14

**Comment by kennycjy** [comment]
Is this ought to be closed? Believe that me and Sean had a conversation about how the issues arose from having 1 index contact deleted. I'm unable to duplicate the issue.

**Comment by russelltankaimin** [comment]
> Is this ought to be closed? Believe that me and Sean had a conversation about how the issues arose from having 1 index contact deleted. I'm unable to duplicate the issue.

U mean reproduce the step? Same here. Not sure what tester actually did. Or he/she didnt give the full story.
