### ISSUE TITLE
UG/DG changes

### ISSUE THREAD

**Issue by russelltankaimin** [AY2223S2-CS2103T-W14-2/tp#352]
# Post any mistakes you see in UG/DG here

**Comment by russelltankaimin** [comment]
### [UG] Fix English

![Screenshot 2023-04-09 at 4 41 47 AM](https://user-images.githubusercontent.com/50812868/230741798-b6e24274-89a9-4fcf-ad5b-e61583c887f1.png)

**Comment by russelltankaimin** [comment]
[UG] Awkward Sentence Structure

![image](https://user-images.githubusercontent.com/50812868/230742013-fc204c58-092a-420a-bea2-bf897783e5cc.png)

**Comment by russelltankaimin** [comment]
## [UG] Fix American English spelling

![image](https://user-images.githubusercontent.com/50812868/230742065-cdba9990-721b-4353-a7a9-2887c42eb996.png)

**Comment by russelltankaimin** [comment]
## [UG] Standardise EduMate appearance
![Screenshot 2023-04-09 at 4 55 24 AM](https://user-images.githubusercontent.com/50812868/230742232-e81eb63d-8e56-4d36-941c-8b09eb9ad124.png)

**Comment by russelltankaimin** [comment]
## [UG] Standardise `EduMate` appearance
![Screenshot 2023-04-09 at 4 58 41 AM](https://user-images.githubusercontent.com/50812868/230742334-c8339eb5-6476-45d5-9f06-af2d95233291.png)

**Comment by russelltankaimin** [comment]
## [UG] Same *number* as you
![image](https://user-images.githubusercontent.com/50812868/230742459-609f474e-a3dc-4023-8764-7a335f216482.png)

**Comment by russelltankaimin** [comment]
## [UG] Missing word **index**
![Uploading Screenshot 2023-04-09 at 5.05.17 AM.png…]()

**Comment by russelltankaimin** [comment]
[UG] Punctuation errors

## Missing Question Mark
![image](https://user-images.githubusercontent.com/50812868/230742713-72ec7b2c-fe0f-4ca8-b2cb-205934e434ef.png)

**Comment by zichen-3974** [comment]
**DG**

**1. More American english** spacing needed between Junit5 and for (3rd image)
> 1. <img width="711" alt="image" src="https://user-images.githubusercontent.com/97385559/230752525-4b887ee7-eb77-44fb-b486-72de84110fed.png">
> 2. <img width="664" alt="image" src="https://user-images.githubusercontent.com/97385559/230752680-e590462d-1e3f-4621-b04e-59a2243076d6.png">
> 3. <img width="693" alt="image" src="https://user-images.githubusercontent.com/97385559/230752839-7f6af16a-fd64-4a41-8ebd-7f16abfcb480.png">




**2. Add one line for Image and Icon credit in Acknowledgements:**
> Some icons and graphics used were sourced from [upklyak](https://www.freepik.com/free-vector/pensive-people-think-about-question-problem-vector-flat-set-curious-doubt-confused-puzzled-women-men-with-hand-head-chin-expression-people-making-decision-choice_23639641.htm) and [flaticon](https://www.flaticon.com) 

**3. Small change, add a space between ui and folder**
> <img width="672" alt="image" src="https://user-images.githubusercontent.com/97385559/230752718-f3616125-01cf-475b-b557-d55b4df343c9.png">

**4. Typo**
> <img width="688" alt="image" src="https://user-images.githubusercontent.com/97385559/230752780-799bd367-185c-4398-9bc7-35e697d04e64.png">

**Comment by zichen-3974** [comment]
### **UG**

**1. More American english**
> 1. <img width="683" alt="image" src="https://user-images.githubusercontent.com/97385559/230753353-0feaf840-28ae-4037-8975-d695c1d08bab.png">
> 2. <img width="668" alt="image" src="https://user-images.githubusercontent.com/97385559/230753364-5a331620-3bd1-4c08-b847-55d8a83b3467.png">
> 3. Already pointed out above, but note theres 2 spellings to change.  <img width="642" alt="image" src="https://user-images.githubusercontent.com/97385559/230753437-a56628a7-8aff-4157-af5e-948408b6ca73.png">
> 4. <img width="674" alt="image" src="https://user-images.githubusercontent.com/97385559/230753547-e5eebfad-c15d-4727-a166-8350597c979d.png">

**2. Spacing needed**
> <img width="667" alt="image" src="https://user-images.githubusercontent.com/97385559/230753491-c8b06b0b-65e1-4f82-9b4b-55bc17c1f99c.png">
> <img width="542" alt="image" src="https://user-images.githubusercontent.com/97385559/230753501-1859298e-f486-40e3-8bed-9b652ad52a3a.png">

**Comment by mynameizzhafeez** [comment]
![Screenshot 2023-04-09 at 4 19 29 PM](https://user-images.githubusercontent.com/37770501/230762136-6b7b127f-056f-4eb2-902a-02e7e75ecab8.png)

Ok back to the Sort Command. For ascending/descending, the only arguments that work are `z/`, `z/a`, `z/d`, `z/A`, `z/D`, `z/aahjklfdsh`, `z/dkrejlhjsfd`. So probably can add that to the Sort Command UG.

**Comment by seanfirefox** [comment]
User Guide does not state that the commands are CASE-SENSITIVE.

**Comment by russelltankaimin** [comment]
> ### [UG] Fix English
> #### 1.
> ![Screenshot 2023-04-09 at 4 41 47 AM](https://user-images.githubusercontent.com/50812868/230741798-b6e24274-89a9-4fcf-ad5b-e61583c887f1.png)
> 
> #### 2.
> ![Screenshot 2023-04-09 at 5 05 17 AM](https://user-images.githubusercontent.com/50812868/230742504-ba98015c-4660-43ae-8b42-67450cc1568e.png)
> 
> #### 3. Awkward sentence structure
> ![image](https://user-images.githubusercontent.com/50812868/230742013-fc204c58-092a-420a-bea2-bf897783e5cc.png)
> 
> #### 4. Fix American English
> ![image](https://user-images.githubusercontent.com/50812868/230742065-cdba9990-721b-4353-a7a9-2887c42eb996.png)
> 
> #### 5. Instead of end, use quit
> ![Screenshot 2023-04-09 at 5 10 09 AM](https://user-images.githubusercontent.com/50812868/230742682-fb72785b-8802-480f-98d5-8cda0b835078.png)

Done

**Comment by russelltankaimin** [comment]
> ## [UG] Standardise `EduMate` appearance
> ![Screenshot 2023-04-09 at 4 58 41 AM](https://user-images.githubusercontent.com/50812868/230742334-c8339eb5-6476-45d5-9f06-af2d95233291.png)

Done
