### ISSUE TITLE
Change Module display to use pipes "|" instead of ArrayList representation.

### ISSUE THREAD

**Issue by russelltankaimin** [AY2223S2-CS2103T-W14-2/tp#49]
Current situation:

<img width="564" alt="Screenshot 2023-02-20 at 10 34 15 PM" src="https://user-images.githubusercontent.com/50812868/220134975-ccce9769-76b9-4caa-b5bc-6420ad56b952.png">

Needs:
![telegram-cloud-photo-size-5-6314204865970156170-x](https://user-images.githubusercontent.com/50812868/220135206-172917d3-931c-4f0b-b549-7c4f84ed5f7d.jpg)

**Comment by mynameizzhafeez** [comment]
@russelltankaimin Will you be doing this?

**Comment by russelltankaimin** [comment]
Yes. But not today.
